{
 "title": "Dashboard",
 "description": "Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Requests Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (http_request_duration_seconds_count{status_code=~\"^[4,5]..$\"})) / (sum (http_request_duration_seconds_count)) * 100"
    }
   ]
  },
  {
   "title": "Request Per Minute",
   "type": "graph",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (irate(http_request_duration_seconds_count{status_code=~\"200|304\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Service Routes Used Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (http_request_duration_seconds_count{status_code=~\"200|304\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 10 API calls (by path) In Last 24 hours",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (max_over_time(http_request_duration_seconds_count[24h])) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Cumulative Request Last Minute",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(http_request_duration_seconds_count[1m]) * 60) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 10 API Error Calls ( 5XX and 4XX, by path)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (max_over_time(http_request_duration_seconds_count{status_code=~\"^[4,5]..$\"}[24h])) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Cumulative Request Last 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (rate(http_request_duration_seconds_count[5m]) * 60) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^5..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^4..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^2..$\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum (irate(http_request_duration_seconds_count{status_code=~\"^3..$\"}[1m]))",
     "legendFormat": "3XX Success Rate"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"+inf\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 1ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.003\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 3ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.03\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 30ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.1\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"0.3\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 300ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"1.5\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 1500ms (%)"
    },
    {
     "expr": "( sum(irate(http_request_duration_seconds_bucket{le=\"10\"}[1m])) /  sum(irate(http_request_duration_seconds_bucket[1m])) ) * 100",
     "legendFormat": "Duration < 10000ms (%)"
    }
   ]
  }
 ]
}