# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
          - node_exporter:9100

  - job_name: kong
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'kong:8001'

  - job_name: 'node-express'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'node-fcm:8088'
