version: '3.8'

networks:
  kong-net:
    external: true

services:
  #######################################
  # Node FCM Service
  #######################################
  node-fcm:
    image: winz7/node-fcm
    restart: always
    environment:
      - TZ=Asia/Bangkok
    networks:
      - kong-net
    ports:
      - '8088:8088'
